// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- Generated by OpenNext during the Cloudflare build.
import { default as nextHandler } from './.open-next/worker.js'
import { Resend } from 'resend'
import type { TransactionalEmailJob } from './lib/email/types'
import { reconcileNotificationOutbox } from './lib/email/queue'
import { expirePendingOrders } from './lib/orders/maintenance'
import { rebuildRecommendationModel } from './lib/recommendations'

function escapeHtml(value: unknown): string {
  return String(value ?? '').replace(/[&<>'"]/g, (character) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;',
  })[character]!)
}

function emailContent(job: TransactionalEmailJob) {
  const orderNumber = escapeHtml(job.payload.orderNumber)
  const name = escapeHtml(job.payload.name || 'there')
  const url = escapeHtml(job.payload.url)
  const status = escapeHtml(job.payload.status)
  const whatsapp = 'https://wa.me/96181492994'

  switch (job.template) {
    case 'verify-email':
      return {
        subject: 'Verify your Enchanted Style account',
        text: `Hi ${name}, verify your email: ${job.payload.url}`,
        html: `<p>Hi ${name},</p><p>Verify your email to finish creating your Enchanted Style account.</p><p><a href="${url}">Verify email</a></p>`,
      }
    case 'reset-password':
      return {
        subject: 'Reset your Enchanted Style password',
        text: `Hi ${name}, reset your password: ${job.payload.url}`,
        html: `<p>Hi ${name},</p><p>Use this secure link to reset your Enchanted Style password.</p><p><a href="${url}">Reset password</a></p>`,
      }
    case 'order-received':
      return {
        subject: `We received order ${orderNumber}`,
        text: `Your order ${job.payload.orderNumber} is awaiting confirmation. Enchanted Style WhatsApp: +961 81 492 994.`,
        html: `<p>We received order <strong>${orderNumber}</strong>.</p><p>It is awaiting confirmation. We will email you when its status changes.</p><p>Need help? <a href="${whatsapp}">Contact Enchanted Style on WhatsApp: +961 81 492 994</a>.</p>`,
      }
    case 'order-status':
      return {
        subject: `Order ${orderNumber}: ${status}`,
        text: `Order ${job.payload.orderNumber} is now ${job.payload.status}. Enchanted Style WhatsApp: +961 81 492 994.`,
        html: `<p>Order <strong>${orderNumber}</strong> is now <strong>${status}</strong>.</p><p>Need help? <a href="${whatsapp}">Contact Enchanted Style on WhatsApp: +961 81 492 994</a>.</p>`,
      }
  }
}

async function sha256(value: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value))
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join('')
}

export default {
  fetch: nextHandler.fetch,
  async queue(batch, env) {
    if (!env.RESEND_API_KEY || !env.RESEND_FROM_EMAIL) {
      const now = new Date()
      for (const message of batch.messages) {
        await env.DB.prepare(
          `UPDATE notification_outbox
           SET status = 'failed', attempts = attempts + 1,
               last_error_code = 'RESEND_NOT_CONFIGURED', available_at = ?, updated_at = ?
           WHERE idempotency_key = ?`,
        ).bind(
          new Date(now.getTime() + 60 * 60 * 1000).toISOString(),
          now.toISOString(),
          message.body.idempotencyKey,
        ).run()
        message.retry()
      }
      return
    }
    const resend = new Resend(env.RESEND_API_KEY)

    for (const message of batch.messages) {
      const job = message.body
      try {
        const existing = await env.DB.prepare(
          'SELECT latest_status FROM email_messages WHERE id = ?',
        ).bind(job.idempotencyKey).first<{ latest_status: string }>()
        if (existing && ['sent', 'delivered'].includes(existing.latest_status)) {
          await env.DB.prepare(
            `UPDATE notification_outbox
             SET status = 'sent', sent_at = coalesce(sent_at, ?), updated_at = ?
             WHERE idempotency_key = ?`,
          ).bind(new Date().toISOString(), new Date().toISOString(), job.idempotencyKey).run()
          message.ack()
          continue
        }

        const now = new Date().toISOString()
        await env.DB.prepare(
          `INSERT INTO email_messages
             (id, template, recipient_hash, latest_status, created_at, updated_at)
           VALUES (?, ?, ?, 'sending', ?, ?)
           ON CONFLICT(id) DO UPDATE SET latest_status = 'sending', updated_at = excluded.updated_at`,
        ).bind(
          job.idempotencyKey,
          job.template,
          await sha256(job.recipient.trim().toLowerCase()),
          now,
          now,
        ).run()

        const content = emailContent(job)
        const result = await resend.emails.send(
          { from: env.RESEND_FROM_EMAIL, to: job.recipient, ...content },
          { idempotencyKey: job.idempotencyKey.slice(0, 256) },
        )
        if (result.error || !result.data?.id) {
          throw new Error(result.error?.name || 'RESEND_SEND_FAILED')
        }

        await env.DB.batch([
          env.DB.prepare(
            `UPDATE email_messages
             SET provider_message_id = ?, latest_status = 'sent', sent_at = ?, updated_at = ?
             WHERE id = ?`,
          ).bind(result.data.id, now, now, job.idempotencyKey),
          env.DB.prepare(
            `UPDATE notification_outbox
             SET status = 'sent', provider_message_id = ?, attempts = attempts + 1,
                 sent_at = ?, updated_at = ?
             WHERE idempotency_key = ?`,
          ).bind(result.data.id, now, now, job.idempotencyKey),
        ])
        message.ack()
      } catch (error) {
        const code = error instanceof Error ? error.message.slice(0, 100) : 'UNKNOWN'
        await env.DB.prepare(
          `UPDATE notification_outbox
           SET status = 'failed', attempts = attempts + 1, last_error_code = ?,
               available_at = ?, updated_at = ?
           WHERE idempotency_key = ?`,
        ).bind(
          code,
          new Date(Date.now() + 15 * 60 * 1000).toISOString(),
          new Date().toISOString(),
          job.idempotencyKey,
        ).run()
        message.retry()
      }
    }
  },
  async scheduled(controller, env, ctx) {
    ctx.waitUntil((async () => {
      try {
        await expirePendingOrders(env.DB)
      } catch (error) {
        console.error('Pending order expiry failed', error)
      }
      await reconcileNotificationOutbox(env)
      if (controller.cron === '17 2 * * *') {
        try {
          await rebuildRecommendationModel(env.DB)
        } catch (error) {
          console.error('Recommendation model rebuild failed', error)
        }
      }
    })())
  },
} satisfies ExportedHandler<CloudflareEnv, TransactionalEmailJob>

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- Generated by OpenNext during the Cloudflare build.
export { DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js'
